---
chapter:
  word: Chapter
  order: standard
section: Section
table: Table
figure: Figure
fig: Figure
aside: Box
listing: Listing
equation: Equation
eq: Eq
frontmatter: Front matter
backmatter: End matter
contents: Contents