sourcedir: sources/original
frontmatter:
  chapters:
  - title: Concept map
    label: concept_map
    sourcefiles:
    - 00_frontmatter/concept_map.tex
  - title: Preface
    label: sec:preface
    sourcefiles:
    - 00_frontmatter/preface.tex
  - title: Introduction
    label: sec:introduction
    sourcefiles:
    - 00_frontmatter/introduction.tex
mainmatter:
  chapters:
  - title: Math fundamentals
    label: chapter:math_fundamentals
    sourcefiles:
    - 01_math/00.math_fundamentals.tex
    - 01_math/01.solving_equations.tex
    - 01_math/02.numbers.tex
    - 01_math/22.hyperbola.tex
    - problems/chapter1_problems.tex
  - title: The second chapter
    label: cha:a_chapter
    sourcefiles:
    - 02_sample/a_chapter.tex
  - title: Vectors
    label: chapter:vectors
    sourcefiles:
    - 03_vecs/00.vectors.tex
    - 03_vecs/02.vectors.tex
    - problems/chapter3_problems.tex
backmatter:
  chapters:
  - title: End matter
    label: chaptxer:end_matter
    sourcefiles:
    - 99_endmatter/end_matter.tex
  - title: Answers and solutions
    label: appendix:ans_and_solutions
    sourcefiles:
    - 99_endmatter/appendix_ans_and_sols_to_probs.tex
  - title: Notation
    label: appendix:notation
    sourcefiles:
    - 99_endmatter/appendix_notation.tex
includes:
- problems/chapter1_numbers_exercises.tex
- problems/chapter3_exercises_vectors.tex
- 99anssol/eanswers_ch1.tex
- 99anssol/esolutions_ch1.tex
- 99anssol/answers_ch1.tex
- 99anssol/solutions_ch1.tex
- 99anssol/eanswers_ch2.tex
- 99anssol/esolutions_ch2.tex
- 99anssol/answers_ch2.tex
- 99anssol/solutions_ch2.tex
- 99anssol/answers_ch3.tex
- 99anssol/solutions_ch3.tex
graphics:
- figures/concept_maps/concept_map_full3.pdf
- figures/dot/chap_prereqs.png
- figures/concept_maps/precalculus.pdf
- figures/math/nested_sets.png
- figures/math/conic_sections_four-shapes.png
- figures/vectors/vector_components.png
- figures/vectors/vector_components_annotated.png
